Update autopromote requirements.txt to pin types-python-dateutil
Installing Python dependencies is failing due to...

```
Collecting types-python-dateutil>=2.8.10
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    types-python-dateutil>=2.8.10 from https://files.pythonhosted.org/packages/1c/af/5af2e2a02bc464c1c7818c260606343020b96c0d5b64f637d9e91aee24fe/types_python_dateutil-2.8.19.14-py3-none-any.whl#sha256=f977b8de27787639986b4e28963263fd0e5158942b3ecef91b9335c130cb1ce9 (from arrow==1.3.0->-r it-cpe-repo/autopromote/requirements.txt (line 7))
```